import Layout from '@layouts/Layout';
import Head from 'next/head';
import { data } from 'utils/data';
import _ from 'lodash';
import { NextPage } from 'next';
import { useState } from 'react';
import { MdFilterAlt, MdFilterAltOff } from 'react-icons/md';

const Home: NextPage = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    <Layout>
        <RecogidasDespachos />
    </Layout>
  </>
);

const RecogidasDespachos = () => {

  return (
    <div className='flex h-full w-full flex-col gap-2 p-4'>
      <div className='flex justify-center'>
        <h1>Gestión inventarios</h1>
      </div>
      <div className='flex flex-col items-center justify-center gap-2 md:flex-row md:justify-between'>
        
      </div>
      <DesktopTable />
      <MobileCards />

      <div>Footer</div>

    </div>
  );
};

const DesktopTable = () => {

  return (
    <div className='hidden h-full flex-col md:flex'>
      <div className='flex h-[80vh] justify-center overflow-y-auto p-6'>
        <table className='w-full'>
          <thead>
            <tr>
              <th className='w-1/4'>Identificador</th>
              <th className='w-1/4'>Fecha</th>
              <th className='w-1/4'>Entrada</th>
              <th className='w-1/4'>Salida</th>
            </tr>
          </thead>
          <tbody>
            {/* Contenido de la tabla */}
          </tbody>
        </table>
      </div>
      <div>Paginacion</div>
    </div>
  );
}
  
const MobileCards = () => (
  <div className='grid h-full grid-cols-2 items-center justify-items-center gap-2 sm:grid-cols-4 md:hidden'>
    
  </div>
);

export default Home;
